# Generated by Django 4.0.2 on 2022-06-27 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outbounds', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='otour',
            options={'verbose_name': 'Outbound Tour', 'verbose_name_plural': 'Outbound Tours'},
        ),
        migrations.RemoveField(
            model_name='price',
            name='age',
        ),
        migrations.AlterField(
            model_name='optional',
            name='Child1_price',
            field=models.CharField(help_text='2-5 Years', max_length=200),
        ),
        migrations.AlterField(
            model_name='optional',
            name='Child2_price',
            field=models.CharField(help_text='6-11 Years', max_length=200),
        ),
        migrations.AlterField(
            model_name='optional',
            name='adult_price',
            field=models.CharField(help_text='18+', max_length=200),
        ),
        migrations.AlterField(
            model_name='optional',
            name='infant_price',
            field=models.CharField(help_text='1-2 Years', max_length=200),
        ),
    ]
