# Generated by Django 4.0.2 on 2022-06-28 08:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('outbounds', '0002_alter_otour_options_remove_price_age_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inclusions',
            name='tour',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='includes', to='outbounds.otour'),
        ),
        migrations.AlterField(
            model_name='price',
            name='tour',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price', to='outbounds.otour'),
        ),
    ]
