# Generated by Django 3.2.14 on 2022-08-03 13:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('outbounds', '0003_alter_inclusions_tour_alter_price_tour'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otourgallery',
            name='tour',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ogallery', to='outbounds.otour'),
        ),
    ]
