# Generated by Django 3.2.14 on 2022-08-04 06:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('outbounds', '0004_alter_otourgallery_tour'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exclusions',
            name='tour',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='excludes', to='outbounds.otour'),
        ),
    ]
