# Generated by Django 3.2.14 on 2023-01-25 09:50

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('outbounds', '0005_alter_exclusions_tour'),
    ]

    operations = [
        migrations.AddField(
            model_name='otour',
            name='user_wishlist',
            field=models.ManyToManyField(blank=True, related_name='user_wishlist', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='otour',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, help_text='Description of tour', null=True),
        ),
    ]
