# Generated by Django 3.2.14 on 2023-02-10 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outbounds', '0006_auto_20230125_1350'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='otour',
            options={'ordering': ['-date_created'], 'verbose_name': 'Outbound Tour', 'verbose_name_plural': 'Outbound Tours'},
        ),
        migrations.AddField(
            model_name='otour',
            name='lat',
            field=models.DecimalField(blank=True, decimal_places=16, max_digits=22, null=True),
        ),
        migrations.AddField(
            model_name='otour',
            name='long',
            field=models.DecimalField(blank=True, decimal_places=16, max_digits=22, null=True),
        ),
        migrations.AlterField(
            model_name='otour',
            name='badge',
            field=models.CharField(choices=[('Popular', 'Popular'), ('Top Rated', 'Top Rated'), ('Eid Special', 'Eid Special'), ('Christmas', 'Christmas'), ('New Year', 'New Year')], max_length=200),
        ),
    ]
