# Generated by Django 3.2.14 on 2023-02-10 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outbounds', '0007_auto_20230210_1121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otour',
            name='lat',
            field=models.FloatField(blank=True, help_text='Latitude', null=True),
        ),
        migrations.AlterField(
            model_name='otour',
            name='long',
            field=models.FloatField(blank=True, help_text='Longitude ', null=True),
        ),
    ]
