# Generated by Django 4.0.2 on 2022-06-15 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='B2bAgent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agent_code', models.CharField(max_length=25, unique=True)),
                ('agent_credit_limit', models.IntegerField()),
                ('agent_name', models.CharField(max_length=100)),
                ('agent_company_name', models.CharField(max_length=100)),
                ('agent_username', models.CharField(max_length=100)),
                ('agent_email', models.CharField(max_length=100)),
                ('agent_mobile', models.CharField(max_length=100)),
                ('agent_desination', models.CharField(max_length=100)),
                ('agent_city', models.CharField(max_length=100)),
                ('agent_country', models.CharField(max_length=100)),
                ('agent_currency', models.CharField(choices=[('AED', 'AED'), ('INR', 'INR'), ('PKR', 'PKR'), ('IDR', 'IDR')], max_length=100)),
                ('agent_TRN', models.CharField(max_length=100)),
                ('is_active', models.BooleanField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
