# Generated by Django 4.0.2 on 2022-06-24 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('b2b', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='b2bagent',
            name='agent_TRN',
            field=models.CharField(help_text='Tax Registered Number', max_length=100),
        ),
        migrations.AlterField(
            model_name='b2bagent',
            name='agent_code',
            field=models.CharField(blank=True, max_length=25, unique=True),
        ),
    ]
