# Generated by Django 3.1.3 on 2022-01-16 08:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agent_code', models.CharField(blank=True, max_length=10, null=True)),
                ('name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='VisaType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('validity', models.IntegerField()),
                ('multiple_entry', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='VisaPrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField()),
                ('currency', models.CharField(blank=True, choices=[('PKR', 'PKR'), ('AED', 'AED')], default='PKR', max_length=3, null=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='visa.agent')),
                ('visa_type', models.ManyToManyField(to='visa.VisaType')),
            ],
        ),
        migrations.CreateModel(
            name='Visa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guest_name', models.CharField(blank=True, max_length=50, null=True)),
                ('guest_passport_number', models.CharField(blank=True, max_length=25, null=True)),
                ('guest_nationality', models.CharField(blank=True, max_length=50, null=True)),
                ('guest_gender', models.CharField(blank=True, max_length=50, null=True)),
                ('visa_status', models.CharField(choices=[('INPROCESS', 'INPROCESS'), ('APPROVED', 'APPROVED'), ('REJECTED', 'REJECTED')], default='INPROCESS', max_length=10)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='visa.agent')),
                ('visa_price', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='visaprice', to='visa.visaprice')),
                ('visa_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='visatype', to='visa.visatype')),
            ],
        ),
    ]
