# Generated by Django 4.0.2 on 2022-05-28 06:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('visa', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='visa',
            options={'ordering': ['-id']},
        ),
        migrations.AlterField(
            model_name='agent',
            name='agent_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='visa',
            name='agent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visa', to='visa.agent'),
        ),
    ]
