# Generated by Django 4.0.2 on 2022-07-08 06:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DropoffLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='PickupLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(help_text='Description of tour')),
                ('max_seats', models.CharField(max_length=200)),
                ('display_image', models.ImageField(blank=True, null=True, upload_to='')),
                ('slug', models.SlugField(default='null', max_length=150, unique=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True, null=True)),
                ('available', models.BooleanField(default=True)),
                ('dropoff_location', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='transfer.dropofflocation')),
                ('pickup_location', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='transfer.pickuplocation')),
            ],
        ),
    ]
