# Generated by Django 4.0.2 on 2022-07-08 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transfer', '0002_alter_transfer_dropoff_location_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transfer',
            name='dropoff_location',
        ),
        migrations.RemoveField(
            model_name='transfer',
            name='pickup_location',
        ),
    ]
