# Generated by Django 3.2.14 on 2023-02-10 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transfer', '0003_remove_transfer_dropoff_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transfer',
            name='transfer_type',
            field=models.CharField(blank=True, choices=[('Sharing', 'sharing'), ('Private', 'Private')], max_length=20, null=True),
        ),
    ]
