# Generated by Django 4.0.2 on 2022-07-05 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0002_amenities_hotel_hotelbooking_hotelimages_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='display_image',
            field=models.ImageField(blank=True, null=True, upload_to='hotels'),
        ),
    ]
