# Generated by Django 3.2.14 on 2023-02-10 07:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('outbounds', '0008_auto_20230210_1147'),
        ('tour', '0004_auto_20230126_1551'),
        ('cart', '0002_alter_cart_id_alter_cartitem_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='otour',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='otour_cartitems', to='outbounds.otour'),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='tour',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tour_cartitems', to='tour.tour'),
        ),
    ]
