# Generated by Django 3.2.14 on 2023-02-10 07:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('outbounds', '0008_auto_20230210_1147'),
        ('tour', '0004_auto_20230126_1551'),
        ('accounts', '0005_auto_20230128_1553'),
        ('bookings', '0002_alter_booking_id_alter_booktour_id_alter_payment_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='paymentMode',
            field=models.CharField(default=12, max_length=70),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='booking',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='booking',
            name='tour',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tour.tour'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.customer'),
        ),
        migrations.AlterField(
            model_name='booktour',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.customer'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.customer'),
        ),
        migrations.CreateModel(
            name='TransferBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_number', models.CharField(max_length=20)),
                ('fullname', models.CharField(max_length=50)),
                ('service_date', models.DateField(blank=True, null=True)),
                ('service_time', models.TimeField(blank=True, null=True)),
                ('phone', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=50)),
                ('pickup_location', models.CharField(max_length=50)),
                ('dropoff_location', models.CharField(blank=True, max_length=100)),
                ('booking_total', models.FloatField(blank=True, null=True)),
                ('tax', models.FloatField(blank=True, null=True)),
                ('status', models.CharField(choices=[('New', 'New'), ('Payment Pending', 'Payment Pending'), ('Booked', 'Booked'), ('Reconfirmed', 'Reconfirmed'), ('Cancelled', 'Cancelled')], default='New', max_length=50)),
                ('paymentMode', models.CharField(blank=True, max_length=70, null=True)),
                ('ip', models.CharField(blank=True, max_length=20)),
                ('is_booked', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.customer')),
            ],
        ),
        migrations.CreateModel(
            name='Obooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_number', models.CharField(max_length=20)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=50)),
                ('country', models.CharField(max_length=50)),
                ('booking_note', models.CharField(blank=True, max_length=100)),
                ('booking_total', models.FloatField()),
                ('tax', models.FloatField()),
                ('status', models.CharField(choices=[('New', 'New'), ('Payment Pending', 'Payment Pending'), ('Booked', 'Booked'), ('Reconfirmed', 'Reconfirmed'), ('Cancelled', 'Cancelled')], default='New', max_length=50)),
                ('paymentMode', models.CharField(max_length=70)),
                ('ip', models.CharField(blank=True, max_length=20)),
                ('is_booked', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to='')),
                ('otour', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='outbounds.otour')),
                ('payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bookings.payment')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.customer')),
            ],
        ),
        migrations.CreateModel(
            name='BookOtour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField()),
                ('booked', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookings.obooking')),
                ('tour', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='outbounds.otour')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.customer')),
            ],
        ),
    ]
